version: "3.9"
services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go_stream_dev
    ports:
      - "5440:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    container_name: gmbm-db-c-dev
  be:
    build:
      context: ./be
      dockerfile: dockerfile.dev
    ports:
      - "3005:3005"
    env_file:
      - ./be/.env
    volumes:
      - ./be:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: gmbm-be-c-dev

  upload-worker:
    build:
      context: ./upload-worker
      dockerfile: dockerfile.dev
    ports:
      - "3009:3009"
    env_file:
      - ./upload-worker/.env
    volumes:
      - ./upload-worker:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: gmbm-upload-worker-c-dev
  fe:
    build:
      context: ./fe
      dockerfile: dockerfile.dev
    ports:
      - "4000:4000"
    env_file:
      - ./fe/.env
    volumes:
      - ./fe:/app  
      - /app/node_modules
    container_name: gmbm-fe-c-dev

  redis-pubsub:
    image: redis:7.4-alpine
    container_name: redis-pubsub-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  websocket:
    build:
      context: ./websocket
      dockerfile: dockerfile.dev
    ports:
      - "9080:8080"
    env_file:
      - ./websocket/.env
    volumes:
      - ./websocket:/app
      - /app/node_modules
    container_name: websocket-dev
    depends_on:
      - redis-pubsub

  sftp:
    image: atmoz/sftp
    volumes:
        - ./upload:/home/foo/upload
    ports:
        - "2222:22"
    command: foo:pass:1001
    container_name: sftp-dev

  rabbitmq:
    image: rabbitmq:3-management
    hostname: dev-rabbitmq-host
    ports:
      - "5677:5672" # RabbitMQ messaging port
      - "15677:15672" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

volumes:
  pgdata-dev:
  redis-data:
  rabbitmq_data:
